# GitHub Dependabot Configuration
#
# Documentation:
#   https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: pip
    directory: /
    groups:
      development-dependencies:
        dependency-type: development
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    groups:
      production-dependencies:
        dependency-type: production
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore:"
    labels:
      - dependencies
    open-pull-requests-limit: 5
