[tox]
envlist =
    py310,

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/src
passenv =
    DATABASE_*
commands = coverage run --rcfile=.coveragerc.test.ini runtests.py tests
deps =
    -r{toxinidir}/requirements_test.txt
basepython =
    py310: python3.10
