# GitHub Actions Workflow for Continuous Integration

name: CI

on:
  workflow_call:

permissions:
  contents: read

env:
  PYTHON_VIRTUALENV_ACTIVATE: venv/bin/activate

jobs:
  pre-build:
    name: Pre-Build
    runs-on: ubuntu-22.04

    steps:
      - run: "true"

  build:
    name: Build
    needs:
      - pre-build
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python_version:
          - "3.9"
          - "3.10"

    steps:
      - name: Check Out VCS Repository
        uses: actions/checkout@v4.2.2

      - name: Set Up Python ${{ matrix.python_version }}
        id: set_up_python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "${{ matrix.python_version }}"
          check-latest: true

      - name: Create Python Virtual Environment
        run: make python-virtualenv PYTHON_VIRTUALENV_DIR="venv"

      - name: Restoring/Saving Cache
        uses: actions/cache@v4.2.2
        with:
          path: "venv"
          key: py-v1-deps-${{ runner.os }}-${{ steps.set_up_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements_test.txt') }}-${{ hashFiles('requirements_release.txt') }}-${{ hashFiles('Makefile', 'make/**.mk') }}

      - name: Install Dependencies
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make install-deps-dev

      - name: Install Library
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make install-dev

  test:
    name: Test
    needs:
      - build
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python_version:
          - "3.9"
          - "3.10"

    services:
      # Database
      #
      # Service container available at `host: localhost`.
      db:
        image: docker.io/library/postgres:15.5-bookworm
        env:
          POSTGRES_DB: accounts_dev_test
          POSTGRES_PASSWORD: "django_dev"
          POSTGRES_USER: django_dev
        options: >- # Set health checks to wait until PostgreSQL has started.
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
         - 5432:5432 # Map TCP port 5432 on service container to the host.

    steps:
      - name: Check Out VCS Repository
        uses: actions/checkout@v4.2.2

      - name: Set Up Python ${{ matrix.python_version }}
        id: set_up_python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "${{ matrix.python_version }}"
          check-latest: true

      - name: Restoring/Saving Cache
        uses: actions/cache@v4.2.2
        with:
          path: "venv"
          key: py-v1-deps-${{ runner.os }}-${{ steps.set_up_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements_test.txt') }}-${{ hashFiles('requirements_release.txt') }}-${{ hashFiles('Makefile', 'make/**.mk') }}
          fail-on-cache-miss: true

      - name: Set Tox Environment
        id: set_tox_environment
        run: |
          # Set Tox environment to the installed Python version.
          tox_env=$(
            python -c 'import sys; v = sys.version_info; print("py{}{}".format(v.major, v.minor))'
          )

          echo "tox_env=${tox_env:?}" >> "$GITHUB_OUTPUT"

      - name: Test
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make test
        env:
          TOXENV: ${{ steps.set_tox_environment.outputs.tox_env }}

      - name: Lint
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make lint

      - name: Test Coverage
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make test-coverage

      - name: Test Coverage Report
        run: |
          source "$PYTHON_VIRTUALENV_ACTIVATE"
          make test-coverage-report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./test-reports/coverage/
          fail_ci_if_error: true

      - name: Store Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.1
        with:
          name: test_reports_${{ matrix.python_version }}
          path: test-reports/
          if-no-files-found: warn

  post-test:
    name: Post-Test
    needs:
      - test
    runs-on: ubuntu-22.04

    steps:
      - run: "true"
